import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Button, EmptyState, LoadingState, PageShell } from '../../../components/ui/EnterpriseUI';
import { platformAdminApi } from '../../../api/platform';

const input = 'admin-input mt-2';
const Field = ({ label, ...props }) => <label className="block text-sm font-medium admin-text-primary">{label}<input {...props} className={input} /></label>;

export default function CourseWorkspace() {
  const { courseId } = useParams(); const navigate = useNavigate();
  const [course, setCourse] = useState(null); const [loading, setLoading] = useState(true); const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const [publishing, setPublishing] = useState(false);
  const [instructors, setInstructors] = useState([]);
  const [lesson, setLesson] = useState({ title: '', content: '', videoUrl: '', order: 1 });
  const [assessment, setAssessment] = useState({ title: '', prompt: '', optionA: '', optionB: '', answer: '0' });
  const [assignment, setAssignment] = useState({ title: '', description: '', maxPoints: 100 });
  const load = () => Promise.allSettled([platformAdminApi.course(courseId), platformAdminApi.users('instructor')]).then(([courseRes, instructorsRes]) => {
    if (courseRes.status === 'fulfilled') {
      setCourse(courseRes.value.data);
      setLesson((current) => ({ ...current, order: (courseRes.value.data.lessons?.length || 0) + 1 }));
    }
    if (instructorsRes.status === 'fulfilled') setInstructors(instructorsRes.value.data || []);
  }).catch((err) => setError(err.message)).finally(() => setLoading(false));
  useEffect(() => { let active = true; Promise.allSettled([platformAdminApi.course(courseId), platformAdminApi.users('instructor')]).then(([courseRes, instructorsRes]) => { if (active) { if (courseRes.status === 'fulfilled') { setCourse(courseRes.value.data); setLesson((current) => ({ ...current, order: (courseRes.value.data.lessons?.length || 0) + 1 })); } if (instructorsRes.status === 'fulfilled') setInstructors(instructorsRes.value.data || []); } }).catch((err) => { if (active) setError(err.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [courseId]);
  const run = async (operation, success) => { setNotice(''); try { await operation(); setNotice(success); await load(); } catch (err) { setNotice(err.message); } };
  const save = (event) => { event.preventDefault(); run(() => platformAdminApi.editCourse(courseId, { title: course.title, description: course.description, category: course.category, level: course.level, price: Number(course.price), thumbnail: course.thumbnail || null, outcomes: course.outcomes || [], instructorId: course.instructorId || course.instructor?.id || '' }), 'Course details saved.'); };
  const changePublication = async () => {
    const nextStatus = course.status === 'approved' ? 'draft' : 'approved';
    setPublishing(true);
    try { await run(() => platformAdminApi.updateCourse(courseId, { status: nextStatus }), nextStatus === 'approved' ? 'Course published and visible to learners.' : 'Course unpublished and removed from the learner catalog.'); }
    finally { setPublishing(false); }
  };
  const openLearnerCourse = () => window.open(`${import.meta.env.VITE_LEARNER_URL || 'http://localhost:3000'}/courses/${courseId}`, '_blank', 'noopener,noreferrer');
  const addLesson = async (event) => { event.preventDefault(); await run(() => platformAdminApi.addLesson(courseId, { ...lesson, order: Number(lesson.order) }), 'Lesson added.'); setLesson({ title: '', content: '', videoUrl: '', order: (course.lessons?.length || 0) + 2 }); };
  const move = (index, direction) => { const next = [...course.lessons]; const target = index + direction; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; run(() => platformAdminApi.reorderLessons(courseId, next.map((item) => item.id)), 'Lesson order saved.'); };
  const editLesson = (item) => { const title = window.prompt('Lesson title', item.title); if (!title) return; const content = window.prompt('Lesson content', item.content); if (content === null) return; run(() => platformAdminApi.updateLesson(courseId, item.id, { title, content }), 'Lesson updated.'); };
  const addAssessment = async (event) => { event.preventDefault(); const options = [assessment.optionA, assessment.optionB]; await run(() => platformAdminApi.createAssessment(courseId, { title: assessment.title, published: true, questions: [{ type: 'multiple_choice', prompt: assessment.prompt, options, answer: options[Number(assessment.answer)], points: 1 }] }), 'Assessment published.'); setAssessment({ title: '', prompt: '', optionA: '', optionB: '', answer: '0' }); };
  const addAssignment = async (event) => { event.preventDefault(); await run(() => platformAdminApi.createAssignment(courseId, { ...assignment, maxPoints: Number(assignment.maxPoints), published: true }), 'Assignment published.'); setAssignment({ title: '', description: '', maxPoints: 100 }); };

  if (loading) return <LoadingState label="Loading course workspace" />;
  if (error || !course) return <EmptyState title="Course unavailable" description={error} action={<Button onClick={() => navigate('/dashboard/admin/courses')}>Back to courses</Button>} />;
  return <PageShell eyebrow="Course workspace" title={course.title} description={`Status: ${course.status} · Changes use the shared learner API.`} actions={<><Button variant="ghost" onClick={() => navigate('/dashboard/admin/courses')}>Back to courses</Button>{course.status === 'approved' && <Button variant="ghost" onClick={openLearnerCourse}>View learner page</Button>}<Button onClick={changePublication} disabled={publishing}>{publishing ? 'Updating…' : course.status === 'approved' ? 'Unpublish course' : 'Publish course'}</Button></>}>
    {notice && <p role="status" className="rounded-xl border border-[var(--admin-border)] bg-[var(--admin-surface)] p-3 text-sm admin-text-primary">{notice}</p>}
    <form onSubmit={save} className="enterprise-card grid gap-4 md:grid-cols-2"><h2 className="section-title md:col-span-2">Course details</h2><Field label="Title" required value={course.title} onChange={(e) => setCourse({ ...course, title: e.target.value })} /><Field label="Category" required value={course.category} onChange={(e) => setCourse({ ...course, category: e.target.value })} /><label className="block text-sm font-medium admin-text-primary md:col-span-2">Description<textarea className={`${input} min-h-28`} required value={course.description} onChange={(e) => setCourse({ ...course, description: e.target.value })} /></label><Field label="Level" value={course.level || 'Beginner'} onChange={(e) => setCourse({ ...course, level: e.target.value })} /><Field label="Price" type="number" min="0" step="0.01" value={course.price || 0} onChange={(e) => setCourse({ ...course, price: e.target.value })} /><Field label="Thumbnail URL" value={course.thumbnail || ''} onChange={(e) => setCourse({ ...course, thumbnail: e.target.value })} /><label className="block text-sm font-medium admin-text-primary">Assigned instructor<select className="admin-select mt-2 w-full" value={course.instructorId || course.instructor?.id || ''} onChange={(e) => setCourse({ ...course, instructorId: e.target.value })}><option value="">Auto-assign least loaded instructor</option>{instructors.map((instructor) => <option key={instructor.id} value={instructor.id}>{instructor.name}</option>)}</select></label><div className="md:col-span-2"><Button>Save course details</Button></div></form>
    <section className="grid gap-5 xl:grid-cols-[1.4fr_1fr]"><div className="enterprise-card"><h2 className="section-title">Curriculum ({course.lessons?.length || 0})</h2><div className="mt-4 space-y-3">{course.lessons?.length ? [...course.lessons].sort((a, b) => a.order - b.order).map((item, index) => <article key={item.id} className="rounded-xl border border-[var(--admin-border)] bg-[var(--admin-surface)] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs admin-text-muted">Lesson {index + 1}</p><h3 className="font-semibold admin-text-primary">{item.title}</h3><p className="mt-1 text-sm admin-text-muted">{item.content}</p></div><div className="flex flex-wrap gap-2"><Button variant="ghost" onClick={() => move(index, -1)} disabled={index === 0}>Up</Button><Button variant="ghost" onClick={() => move(index, 1)} disabled={index === course.lessons.length - 1}>Down</Button><Button variant="ghost" onClick={() => editLesson(item)}>Edit</Button><Button variant="ghost" onClick={() => { if (window.confirm(`Delete ${item.title}?`)) run(() => platformAdminApi.deleteLesson(courseId, item.id), 'Lesson deleted.'); }}>Delete</Button></div></div></article>) : <EmptyState title="No lessons yet" description="Add the first lesson using the form." />}</div></div><form onSubmit={addLesson} className="enterprise-card space-y-4"><h2 className="section-title">Add lesson</h2><Field label="Title" required value={lesson.title} onChange={(e) => setLesson({ ...lesson, title: e.target.value })} /><label className="block text-sm font-medium admin-text-primary">Content<textarea className={`${input} min-h-28`} required value={lesson.content} onChange={(e) => setLesson({ ...lesson, content: e.target.value })} /></label><Field label="Video URL (optional)" value={lesson.videoUrl} onChange={(e) => setLesson({ ...lesson, videoUrl: e.target.value })} /><Button>Add lesson</Button></form></section>
    <section className="grid gap-5 lg:grid-cols-2"><form onSubmit={addAssessment} className="enterprise-card space-y-4"><h2 className="section-title">Publish assessment</h2><Field label="Assessment title" required value={assessment.title} onChange={(e) => setAssessment({ ...assessment, title: e.target.value })} /><Field label="Question" required value={assessment.prompt} onChange={(e) => setAssessment({ ...assessment, prompt: e.target.value })} /><Field label="Option A" required value={assessment.optionA} onChange={(e) => setAssessment({ ...assessment, optionA: e.target.value })} /><Field label="Option B" required value={assessment.optionB} onChange={(e) => setAssessment({ ...assessment, optionB: e.target.value })} /><label className="block text-sm font-medium admin-text-primary">Correct answer<select className="admin-select mt-2 w-full" value={assessment.answer} onChange={(e) => setAssessment({ ...assessment, answer: e.target.value })}><option value="0">Option A</option><option value="1">Option B</option></select></label><Button>Publish assessment</Button></form><form onSubmit={addAssignment} className="enterprise-card space-y-4"><h2 className="section-title">Publish assignment</h2><Field label="Assignment title" required value={assignment.title} onChange={(e) => setAssignment({ ...assignment, title: e.target.value })} /><label className="block text-sm font-medium admin-text-primary">Instructions<textarea className={`${input} min-h-28`} required value={assignment.description} onChange={(e) => setAssignment({ ...assignment, description: e.target.value })} /></label><Field label="Maximum points" type="number" min="1" required value={assignment.maxPoints} onChange={(e) => setAssignment({ ...assignment, maxPoints: e.target.value })} /><Button>Publish assignment</Button></form></section>
  </PageShell>;
}
